

annotation_path: /workspace/data/annotations.jsonl
video_dir: /workspace/data/videos
output_dir: /workspace/logs/submit

parser_version: "v2" # "v1" or "v2"
max_task_num: 1


debug_mode: true
target_subclass: "Dolly in" # "Zoom in"


# ----------------------------------------------------#
# unused
groundingdino:
  config_path: /workspace/third_party/GroundingDINO/groundingdino/config/GroundingDINO_SwinT_OGC.py
  checkpoint: /workspace/weights/groundingdino/groundingdino_swint_ogc.pth

sam:
  checkpoint: /workspace/weights/sam/sam_vit_h_4b8939.pth

zoom_in:
  zoom_factor: 1.0